### ISSUE TITLE
opencare proposal pdf

### ISSUE THREAD

**Issue by LuceChiodelliUB** [opencarecc/OpenCareLandingPage#84]
Hello, 

Just a word to say I've had a look at your landing page, and it's amazing work :) 

Just one thing I noticed: the project proposal available on the edgeryders website is not the final version we all signed (edgeryders still appears as the project coordinator for example).

The correct version is available under [opencare > proposal -final > opencare_DoA.pdf](https://drive.google.com/open?id=0BxnwAmGNB9t9cTFKT3NLWEFWbXM)

I've made for the EC 2 documents to describe opencare - I shared them here, in case you may need them.  
They are available under 
[opencare > opencare admin > presentation ](https://drive.google.com/open?id=0BxnwAmGNB9t9dkNoSlc1VkpIRk0)
[opencare > opencare admin > fact sheet](https://drive.google.com/open?id=0BxnwAmGNB9t9ZW1xcjVaRTVBMjA)

Thanks :) 
Luce

**Comment by kostasprint** [comment]
Hi Luce, 

the correct pdf (wichever it is) has to be uploaded on editing page directly on Edgeryders. 
I've done it for all of us. 

by the way: 
can we amend the presentation and the factsheet according to the final decision about naming and website: 
**opencare**
opencare.cc
?

c

**Comment by LuceChiodelliUB** [comment]
Hello, 

I'll ask Alberto for an update, no pb.

I can sure change the documents - but I have sent them to the EC for publishing before we had the trademark discussion. I'll ask if they agree to charge a new version on their websites.
